config/routes.rb
Infp::Application.routes.draw do
  resources :pages

  root to: 'pages#home', as: 'home'
  get :reasons, to:'pages#reasons', as:'reasons'
  get :terms, to:'pages#terms', as: 'terms'
  get :privacy, to:'pages#privacy', as: 'privacy'
  get :takedown, to:'pages#takedown', as: 'takedown'
  get :forbidden, to:'pages#forbidden', as: 'forbidden'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  # 'Static' pages  =================================================
  def home

  end

  def reasons
  end

  def forbidden
  end

  # Footer links =================================================
  def terms # Terms of use
  end

  def privacy # Privacy policy
  end

  def takedown # DMCA takedown policy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.slim
doctype html
html.fill-height
  head
    / meta tags
    == yield :head

    / styles
    == render 'layouts/partials/headstyles'
    == yield :extra_stylesheets

    / scripts
    == render 'layouts/partials/headscripts'
    == yield :head_javascripts

  body.fill-height.background
    == render 'layouts/partials/standardModals'
    == yield :extra_modals

    / Top navbar goes here
    == render 'layouts/partials/navbar'

    .container.pad-top-lg
      / Body goes here
      == yield

    / Footer goes here
    == render 'layouts/partials/footer'
    
    == yield :end
    == render 'layouts/partials/bottomScripts'

app/views/layouts/partials/_dropdown.html.slim
li.dropdown
  a.dropdown-toggle.nav-link href="#" data-toggle="dropdown" 
    .nav-link
      | &nbsp;
      | Placeholder
      /- if !current_user.first_name.blank?
        /= current_user.first_name
      /- else
        /= current_user.email
      b.caret
  ul.dropdown-menu
    li = link_to "Your Home Page", home_path

app/views/layouts/partials/_headscripts.html.slim
= include_gon
= javascript_include_tag "application", "data-turbolinks-track" => true
= csrf_meta_tags
meta name="viewport" content="width=device-width, initial-scale=1.0"

app/views/layouts/partials/_headstyles.html.slim
= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
link href='http://fonts.googleapis.com/css?family=Monda' rel='stylesheet' type='text/css'

app/views/layouts/partials/_navbar.html.slim
/ This isn't really done properly for mobile.  Should be fixed later.
nav.navbar.navbar-fixed-top.navbar-inverse.navbar-color.navbar-border role="navigation"
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="#bs-collapsable"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      /a.navbar-brand.brand href=home_path camp&Lambda;wesome
      a.navbar-brand.brand href=home_path INFP Joy
    / Collect the nav links, forms, and other content for toggling
    #bs-collapsable.collapse.navbar-collapse
      / Left Navbar section
      /= render 'layouts/searchNav'
      
      / Navbar pulled right
      ul.nav.navbar-nav.navbar-right
        /- if user_signed_in?
          /= render 'layouts/dropdown'
        /- else
          /li = link_to 'Sign up', new_user_registration_path, class:"nav-link"
          /a href=new_user_registration_path
            /button.btn.btn-success Sign Up
          /li = link_to 'Sign in', new_user_session_path, class:"nav-link"
          li.nav-link
            a#signupTrigger href="#" data-toggle="modal" data-target="#signupModal" 
              .nav-link Sign up
          li.nav-link
            a#signinTrigger href="#" data-toggle="modal" data-target="#signinModal" 
              .nav-link Sign in

app/views/pages/home.html.slim
- content_for :head
  title Joy (for INFPs)
  meta name="keywords" content="INFP"
  meta name="description" content="A website by INFPs for INFPs."

/ Main content
h1.text-center.col-md-12
  | Hello lovely person.  Are you an INFP?  There's an ecclectic app for that!
p.col-md-12 Here's what I've got for you:
ul.col-md-12
  li Articles, blogs, and other nice stuff written for INFPs by INFPs
  li A community of users who get you.  Because guess what!  They're INFPs too.  
  li A place to show off your imagination to like-minded individuals. Share messages, art, music, poetry, apps, whatever you want.
  li Yes, it's free!
p.col-md-12 Why?
p.col-md-12 Being an INFP isn't easy.  Let's face it.  You're really fricking weird and most people don't get you.  If you're not daydreaming or talking to an imaginary person you invented for the very specific conversation, then you probably were 10 seconds ago.  That's okay.  Even though we only make up 1-3% of the US population, there's a lot of us.